
alg_name: "FT"
model_name: "/workspace/models/Qwen/Qwen2.5-7B-Instruct"
device: 0
layers: [27]
num_steps: 5
lr: 1e-5
weight_decay: 0
kl_factor: 0
norm_constraint: 5e-4
max_grad_norm: 1.0
rewrite_module_tmp: "model.layers.{}.mlp.down_proj.weight"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"
objective_optimization: 'target_new'
batch_size: 10
max_length: 256
